- name: nginx | Copy site configs
  copy:
    src: ./resources/config/{{ item }}
    dest: /etc/nginx/sites-available/{{ item }}
    mode: 0644
  with_items:
    - nodejs.org
    - iojs.org
    - libuv.org
    - benchmarking.nodejs.org
  tags: nginx

- name: nginx | Create nginx config symlinks
  file:
    src: '/etc/nginx/sites-available/{{ item.src }}'
    dest: '/etc/nginx/sites-enabled/{{ item.dest }}'
    state: link
  with_items:
    - { src: nodejs.org, dest: 00-nodejs.org }
    - { src: iojs.org, dest: 01-iojs.org }
    - { src: libuv.org, dest: 02-libuv.org }
    - { src: benchmarking.nodejs.org, dest: 03-benchmarking.nodejs.org }
  tags: nginx

- name: nginx | Make /etc/nginx/ssl/
  file:
    path: /etc/nginx/ssl/
    state: directory
    mode: 0755
    owner: root
  tags: nginx

- name: nginx | Copy site certificates
  copy:
    src: ./resources/secrets/{{ item }}
    dest: /etc/nginx/ssl/{{ item }}
    mode: 0644
  with_items:
    - nodejs_chained.crt
    - iojs_chained.crt
    - nodejs.key
    - iojs.key
    - dhparam.pem
  tags: nginx

- name: nginx | Install shared ssl defaults
  copy:
    src: ./resources/config/ssl-defaults.conf
    dest: /etc/nginx/conf.d/ssl-defaults.conf
  tags: nginx

- name: nginx | Remove ssl_protocols from default nginx config
  replace:
    dest: /etc/nginx/nginx.conf
    regexp: '^(\s+)ssl_protocols'
    replace: '\1# ssl_protocols'
  tags: nginx

- name: nginx | Install open file cache config
  copy:
    src: ./resources/config/open-file-cache.conf
    dest: /etc/nginx/conf.d/open-file-cache.conf
    mode: 0644
  tags: nginx

- name: nginx | Delete default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags: nginx

- name: nginx | Add extra mime-type
  lineinfile:
    dest: /etc/nginx/mime.types
    line: '{{ item }}'
    insertafter: '^types.*'
  with_items:
    - 'application/octet-stream pkg;'
    - 'application/x-xz xz;'
    - 'application/gzip gz;'
  tags: nginx

- name: nginx | Copy nginx logrotate config
  copy:
    src: ./resources/config/logrotate-nginx
    dest: /etc/logrotate.d/nginx
    mode: 0644
    owner: root
    group: root
  tags: nginx

- name: nginx | Make /var/log/nginx/ subdirectories
  file:
    path: '/var/log/nginx/{{ item }}'
    state: directory
    mode: 0755
    owner: www-data
    group: adm
  with_items:
      - 'nodejs'
      - 'iojs'
      - 'libuv'
      - 'benchmarking'
  tags: nginx

- name: nginx | Restart service
  service:
    name: nginx
    state: restarted
    enabled: yes
  tags: nginx
