- name: nightly-builder | Install nightly-builder
  command: "npm install nodejs-nightly-builder -g"
  tags: nightly-builder

- name: nightly-builder | Copy config
  copy:
    src: ./resources/config/nightly-builder.json.j2
    dest: /etc/nightly-builder.json
    mode: 0644
  tags: nightly-builder

  #TODO: the branches are hardwired here, they should be in vars somewhere
- name: nightly-builder | Add periodic tasks to crontab
  lineinfile:
    dest: /etc/crontab
    line: "{{ item }}"
  with_items:
    - '0 20    * * *   dist    /usr/bin/nodejs-nightly-builder --type nightly --ref heads/v6.x --config /etc/nightly-builder.json'
    - '0 19    * * *   dist    /usr/bin/nodejs-nightly-builder --type nightly --ref heads/v7.x --config /etc/nightly-builder.json'
    - '0 18    * * *   dist    /usr/bin/nodejs-nightly-builder --type nightly --ref heads/master --config /etc/nightly-builder.json'
  tags: nightly-builder
