---
- hosts: node-www
  remote_user: root

  tasks:
    - include_vars: ansible-vars.yaml
      tags: vars

    - include: tasks/base.yaml
      tags: base

    - include: tasks/user.yaml
      tags: user

    - include: tasks/docker.yaml
      tags: docker

    - include: tasks/site-setup.yaml
      tags: setup

    - include: tasks/webhook.yaml
      tags: webhook

    - include: tasks/nginx.yaml
      tags: nginx

    - include: tasks/dist-indexer.yaml
      tags: dist-indexer

    - include: tasks/nightly-builder.yaml
      tags: nightly-builder

    - include: tasks/promote.yaml
      tags: promote

    - include: tasks/latest-linker.yaml
      tags: latest-linker

    - include: tasks/metrics.yaml
      tags: metrics
